name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Cache pip
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Cache PlatformIO
        uses: actions/cache@v2
        with:
          path: ~/.platformio
          key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
      - name: Set up Python
        uses: actions/setup-python@v2
      - name: Install PlatformIO
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade platformio
      - name: Set up GCC
        uses: egor-tensin/setup-gcc@v1
        with:
          version: latest

      - name: Run PlatformIO Sender
        run: pio run -e nanoatmega328 -d ./Sender

      - name: Run PlatformIO Recive
        run: pio run -e nanoatmega328 -d ./Reciver

      - name: palntuml
        id: plantuml
        uses: grassedge/generate-plantuml-action@v1.5
        with:
          path: sender
          message: "Render PlantUML files"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}